[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = "=1.2.1"
serde = "=1.0.152"

[dev-dependencies]
cw-multi-test = "=0.16.2"
